kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: prisma
  commands:
  - npx prisma generate
- name: nextjs build
  commands:
  - npm run build
- name: task build
  commands:
  - npm run task:build
- name: nextjs run
  commands:
  - npm start
- name: task run
  commands:
  - node .task-dist/task/index.js