services:
  nextjs:
    build:
      context: .
      dockerfile: dockerfile
      target: nextjs
    ports:
      - "3000:3000"
  task:
    build: 
      context: .
      dockerfile: dockerfile
      target: task